const ROLES_DEFINITION = {
  CREATE_USER: "CREATE_USER",
  GET_USERS: "GET_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER_ROLE: "UPDATE_USER_ROLE",
  CREATE_PROJECT: "CREATE_PROJECT",
  GET_PROJECTS: "GET_PROJECTS",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
};

const ALL_ROLES = {
  user: [],
  manager: [ROLES_DEFINITION.GET_USERS, ROLES_DEFINITION.CREATE_USER],
  admin: Object.values(ROLES_DEFINITION),
};

const roles = Object.keys(ALL_ROLES);
const roleRights = new Map(Object.entries(ALL_ROLES));

module.exports = {
  roles,
  roleRights,
  ROLES_DEFINITION,
};
